### ISSUE TITLE
so where are the models?

### ISSUE THREAD

**Issue by ilzyy** [AXERA-TECH/SAM-ONNX-AX650-CPP#3]
./main -e ax_models/sam-encoder.axmodel
I just want to test the case , but the model is not provided

**Comment by ZHEQIUSHUI** [comment]
download this zip file,the *.axmodel file include in it
https://github.com/AXERA-TECH/SAM-ONNX-AX650-CPP/releases/download/v1.1/samqt_ax650.zip
